sudo: required
dist: xenial
language: scala
scala:
  - 2.12.10
jdk:
  - openjdk8
services:
  - docker
  - postgresql

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11

cache:
  directories:
  - $HOME/.m2

env:
  global:
    - PGPORT=5433
    # AWS_ACCESS_KEY_ID
    - secure: "A5YhLsl6xZWcrG7ETTi6X9VkLwEZEmZTOikYKGDtts7ryGAYT6IZ5JvLad/XWZWoa+6aEihAe2Sc+oc9ORppp0D/VA0UJ1hWcNcrX+IsS0rDtRO1Y1sHFc18nwSnXCrzKQy9kw5+5VZ2YzisV7PPivyzl0DhYg0GDbW4X3umvfFi6UZ9OhHBkepkdZ3zSYs8ggYixWk5r1Yxu7YYsnmtOUTvxQu/SU0XN4Q0xL9eiJN1Nw5X/qSqFboPoHzYRGRhRZFIT3JvYakGIoShLw7W0krc8RS/cHAXwgXK9+QMSlEVam48+J88Y3v0gX+vfgc7PDL8ZZXRbUu84FEUNBRtDmtao5CncHI2sFzYhOmf+2rgkueyWiGNb/tsmc540wi9zdwflWP1p2LYovKFtVywykLMZ26nxB9QD0vV2ehIMc43H1ard8Y+GQPZjLOBhwenG0fMqtyMunxuagrfBi8BumE7OXCPJW/2E6piIQLitct8RiidnCJaVb+JXFWflrKUapMT9qYg6L1UngJ3OAWZzWsF2ortduMFFj6sAJxrZEOQlAnvmuHtEW+zcZNjboio9TiA6Nb7dyvh3h+hXeIYpAk3ifhxAyYqjTe6JNbGAzwDK7f3IlKBROcEzSzwSBEkDK603N9AaPs80Ahqc6dDm69FzsaC9w5+nFmTCIU2qfw="
    # AWS_SECRET_ACCESS_KEY
    - secure: "hpRAl4znS68nf1HLudmsT6dapNefp1Wu8i6hEVRkvmNXD4Sjq8rbIop2SC3DMBLuq/2s9DwogX0nT544g7YlPYz9Q4QgqKUvEE8LKOHRHZCCxiJMpkUOlUJPWqhzeLCBI8Wh0JQiqvvjnpH9X54buQrdWK6C6Td2RNAaJjP7SHz8uz/wHCgMLlTl4HZ29xwzMM6WE+4t+D44Ed0PU+0srgBunLmzqoEU1eLxvQ8YauV7hnq7LrSd/2cyGCmKO0PSfGYN2X6jlwMde9Aa7ZWkL6iVwqrhuWlq+Tq8/dXIFEEjP74RLigfX5L9zzkNoDxiAT5Kbahhn4y1S9KNiwpth574L+GBn/CfteWs4h0A97wQE4MUxnN+ez8z+B64gYyRhVX559VcGlP3C10K3rwc8ibALQPuoE3lqmVYHpzxgRMFV5BYRjYgpg8g2N+qksPqBkFWzoNOd90IVWSL1h4eO2vPtwr520K5DUOCgsgKSnQlO4wdj5bspUGJ0RqOxICP82BMUtXrb36yb8tTqLcmRP6Mccc39VLLsltgsdewDqHKhRByIfneR0+oO8t1gd0hCgpHv10qhrcumQpUMNDfWmWX0Z1a4jF7QPuQpijc407tIFfQPLTZ4iPIPZUfTaPyOfINNQh9Bteu+dgqVKOETi1xLwmORwsupl1f+/QIcNA="
    # ARTIFACTORY_USERNAME
    - secure: "ZgrEL0Afo/ymsq0qlfxHJiZWwA77A3IIbQwMr3XZiNNls1zAswD51SW/jHWqpTVkfLGWJpaxM5Ljq5sagyMWRxADXx5JayFkDzz7WVz42CfchwiebZP19qXM46HTg3EkNdFf9p776AObwpD9iaw84euUtLUlVzv3Xy9t1hadvnoTC4PfUgItZ1+gH/P2K2eBA8tUB+lMZtFq/nor1LTGnGpRD+A8a+om47UncjsMu45lPflGiW72uvGj2S96MI4jE2A6SK6H7+NoZevZlNbnAoryt3LmIwdzqp6awbHvu7C7Lk5m1H10uM0brHQLMOTh0P5FGH06JoPD7A/p9/wr6rknu/yiBxO/0bsbIlg6CGgx/2cdc3/bGMh/EOtX/klYgo2rVzp9PPOaXkJNTEy0uie8pAG4l+7cpqJe9CgilENaVOLooiphveYK2itNTXgNyb5TIOXXfxHjbVr7+dGyINni9K3qtiA8gxzqpnxql9w+whM6PRDC11McdVBQ0w2jXhR1KAX/V3JYeDEnq+S2lZh3VwajgHITiKUicjDaxv3tSGGHQOLsTgerIPoG11o2j8OuUYwFLwWyngbZPtZhlcBavLLKZsaa4znYFBSocXsaefywCxPgiwqLE6Q2VVhMntF8JWHENMEsX7IO75jqPxUWHC06zZINKpTwGNZSo7E="
    # ARTIFACTORY_PASSWORD
    - secure: "etn73vYrpHhL3EyizDphhAxxzASQd2yVsOl+TVStyqbegAbZwh0ZMkqyLMvK4ktAkub8QEcKdiIea7hWd9/CDmMKhm8KUKCGfN/yHRNH6fVF5vuA0/sbaP6WmzMYkDnPh8iZ5+mJntAQ5QFQ6FLX4Rw0xHjBjZ1tlAyoHL8lyOCXLq9MRP5w2mdbTkzw3Z59Gd/CL83gtaYBulqFOYcgphNCh49j+4cyorwamBGPD5GeRftdAUyDXATB1O2VCppCFfy5fTgBiRXD/lu8ia7faGO5ihohQuS602e0lEZlg177+e9mS1b7MqT2X8W4DjoiycLhJ78JCq2mL+PfTc59KEuB6IBA2Y56y1xT+xouQ7g+bLrEZ9Yyw5SCyytNT5X1LqgT0SSjdnHat3q5nz6qsqw5idqX8Zw0dXA34qN9YmzXwwaCfNkqROGBtRV2XO7HnIBG9PhLod0j2ISCzNBGIF411+mTG6RGRuxWfmcwfJr16BzxB6FTcCrTGutbcTDuZk+iVRl8mPeOyV/HefANplEWCP2rEDtwmjuv8REuGK2AVy8kvGXmNw7i96+iMlBwdKiLg754ejKpy+fPAaAjb4nwFOJ0cbOQihpD0qeyVLdf1SLhJglU8dlhstWTZu2yF+5xMDnQB+vnjXK9U5EzUoQNDxCdoPd6Am8yBL+3Kps="

before_install:
  # https://github.com/travis-ci/travis-ci/issues/9624
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo systemctl restart postgresql@11-main
  - sleep 1

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="kouta-backend"

before_script:
  - DB_NAME=kouta
  - psql -c "create database $DB_NAME WITH ENCODING 'UTF8' LC_COLLATE='C' LC_CTYPE='C' TEMPLATE template0;" -U postgres
  - psql -d $DB_NAME -f kouta-backend/postgresql/init_it_postgresql.sql
  - docker pull localstack/localstack:0.10.2

script:
  - mvn clean package --batch-mode -DargLine="-Dkouta-backend.test-postgres-port=${PGPORT}"

  - mv kouta-backend/target/kouta-backend-*-jar-with-dependencies.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar
  - cp -vr kouta-backend/src/main/resources/* $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-fatjar-openjdk8:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-fatjar.sh $ARTIFACT_NAME

deploy:
  - provider: script
    script:
      mvn deploy -DskipTests --settings ci-tools/common/maven-settings.xml
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script:
      ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
    on:
      all_branches: true

