COMMENT ON SCHEMA public IS 'Opintopolun koulutustarjonnan tiedot';

COMMENT ON TABLE koulutukset IS 'Koulutukset eli koulutusmoduulin toteutukset';
COMMENT ON COLUMN koulutukset.oid IS 'Koulutuksen yksilöivä tunniste. Järjestelmän generoima.';
COMMENT ON COLUMN koulutukset.johtaa_tutkintoon IS 'Onko koulutus tutkintoon johtavaa';
COMMENT ON COLUMN koulutukset.tyyppi IS 'Koulutuksen tyyppi. Sallitut arvot: "amm" (ammatillinen), "yo" (yliopisto), "lk" (lukio), "mk" (ammattikorkea), "muu" (muu koulutus)';
COMMENT ON COLUMN koulutukset.koulutus_koodi_uri IS 'Koulutuksen koodi URI. Viittaa  koodistoon: https://virkailija.testiopintopolku.fi/koodisto-ui/html/koodisto/koulutus/11';
COMMENT ON COLUMN koulutukset.tila IS 'Koulutuksen julkaisutila. Jos koulutus on julkaistu, se näkyy oppijalle Opintopolussa. Sallitut arvot: "julkaistu", "arkistoitu", "tallennettu"';
COMMENT ON COLUMN koulutukset.nimi IS 'Koulutuksen Opintopolussa näytettävä nimi eri kielillä. Kielet on määritetty koulutuksen kielivalinnassa. Esim: "{"fi": "Suomenkielinen nimi", "sv": "Ruotsinkielinen nimi", "en": "Englanninkielinen nimi"}"';
COMMENT ON COLUMN koulutukset.metadata IS 'Yleistä koulutukseen liittyvää metadataa kuten koulutusalat, kuvaukset, lisätietoja, tutkintonimikkeet, opintojen laajuus ja koulutustyyppi.';
COMMENT ON COLUMN koulutukset.muokkaaja IS 'Koulutusta viimeksi muokanneen virkailijan henkilö-oid';
COMMENT ON COLUMN koulutukset.transaction_id IS 'Transaktion, jossa viimeksi muokattu, tunniste';
COMMENT ON COLUMN koulutukset.system_time IS 'Koulutuksen viimeisin muokkausaika. Järjestelmän generoima';
COMMENT ON COLUMN koulutukset.kielivalinta IS 'Kielet, joille koulutuksen nimi, kuvailutiedot ja muut tekstit on käännetty';
COMMENT ON COLUMN koulutukset.organisaatio_oid IS 'Koulutuksen luoneen organisaation oid';
COMMENT ON COLUMN koulutukset.julkinen IS 'Voivatko muut oppilaitokset käyttää koulutusta';

COMMENT ON TABLE toteutukset IS 'Koulutusten toteutukset eli koulutusmoduulin toteutukset';
COMMENT ON COLUMN toteutukset.oid IS 'Toteutuksen yksilöivä tunniste. Järjestelmän generoima.';
COMMENT ON COLUMN toteutukset.koulutus_oid IS 'Toteutukseen liittyvän koulutuksen yksilöivä tunniste';
COMMENT ON COLUMN toteutukset.tila IS 'Toteutuksen julkaisutila. Jos toteutus on julkaistu, se näkyy oppijalle Opintopolussa. Sallitut arvot: "julkaistu", "arkistoitu", "tallennettu"';
COMMENT ON COLUMN toteutukset.nimi IS 'Toteutuksen Opintopolussa näytettävä nimi eri kielillä. Kielet on määritetty koulutuksen kielivalinnassa. Esim: "{"fi": "Suomenkielinen nimi", "sv": "Ruotsinkielinen nimi", "en": "Englanninkielinen nimi"}"';
COMMENT ON COLUMN toteutukset.metadata IS 'Yleistä koulutukseen liittyvää metadataa kuten kuvaus, tietoja opetuksen järjestämisestä sekä maksullisuudesta, yhteyshenkilö, asiasanat, ammattinimikkeet, osaamisalat ja koulutustyyppi.';
COMMENT ON COLUMN toteutukset.muokkaaja IS 'Toteutusta viimeksi muokanneen virkailijan henkilö-oid';
COMMENT ON COLUMN toteutukset.transaction_id IS 'Transaktion, jossa viimeksi muokattu, tunniste';
COMMENT ON COLUMN toteutukset.system_time IS 'Toteutuksen viimeisin muokkausaika. Järjestelmän generoima';
COMMENT ON COLUMN toteutukset.kielivalinta IS 'Kielet, joille toteutuksen nimi, kuvailutiedot ja muut tekstit on käännetty';
COMMENT ON COLUMN toteutukset.organisaatio_oid IS 'Toteutuksen luoneen organisaation oid';

COMMENT ON TABLE hakukohteet IS 'Hakukohteet';
COMMENT ON COLUMN hakukohteet.oid IS 'Hakukohteen yksilöivä tunniste. Järjestelmän generoima.';
COMMENT ON COLUMN hakukohteet.toteutus_oid IS 'Hakukohteeseen liitetyn toteutuksen yksilöivä tunniste.';
COMMENT ON COLUMN hakukohteet.haku_oid IS 'Hakukohteeseen liitetyn haun yksilöivä tunniste.';
COMMENT ON COLUMN hakukohteet.tila IS 'Haun julkaisutila. Jos hakukohde on julkaistu, se näkyy oppijalle Opintopolussa. Sallitut arvot: "julkaistu", "arkistoitu", "tallennettu"';
COMMENT ON COLUMN hakukohteet.nimi IS 'Hakukohteen Opintopolussa näytettävä nimi eri kielillä. Kielet on määritetty koulutuksen kielivalinnassa. Esim: "{"fi": "Suomenkielinen nimi", "sv": "Ruotsinkielinen nimi", "en": "Englanninkielinen nimi"}"';
COMMENT ON COLUMN hakukohteet.alkamiskausi_koodi_uri IS 'Hakukohteen koulutusten alkamiskausi, jos ei käytetä haun alkamiskautta. Viittaa koodistoon: https://virkailija.testiopintopolku.fi/koodisto-ui/html/koodisto/kausi/1';
COMMENT ON COLUMN hakukohteet.alkamisvuosi IS 'Hakukohteen koulutusten alkamisvuosi, jos ei käytetä haun alkamisvuotta';
COMMENT ON COLUMN hakukohteet.hakulomaketyyppi IS 'Hakulomakkeen tyyppi. Kertoo, käytetäänkö Atarun (hakemuspalvelun) hakulomaketta, muuta hakulomaketta (jolloin voidaan lisätä hakulomakkeeseen linkki) tai onko niin, ettei sähkököistä hakulomaketta ole lainkaan, jolloin sille olisi hyvä lisätä kuvaus.';
COMMENT ON COLUMN hakukohteet.hakulomake_kuvaus IS 'Hakulomakkeen kuvausteksti eri kielillä. Kielet on määritetty haun kielivalinnassa.';
COMMENT ON COLUMN hakukohteet.aloituspaikat IS 'Hakukohteen aloituspaikkojen lukumäärä';
COMMENT ON COLUMN hakukohteet.ensikertalaisen_aloituspaikat IS 'Hakukohteen ensikertalaisen aloituspaikkojen lukumäärä';
COMMENT ON COLUMN hakukohteet.pohjakoulutusvaatimus_koodi_urit IS 'Lista toisen asteen hakukohteen pohjakoulutusvaatimuksista. Viittaa koodistoon: https://virkailija.testiopintopolku.fi/koodisto-ui/html/koodisto/pohjakoulutusvaatimustoinenaste/1';
COMMENT ON COLUMN hakukohteet.muu_pohjakoulutusvaatimus_kuvaus IS 'Hakukohteen muiden pohjakoulutusvaatimusten kuvaus eri kielillä. Kielet on määritetty koulutuksen kielivalinnassa.';
COMMENT ON COLUMN hakukohteet.toinen_aste_onko_kaksoistutkinto IS 'Onko hakukohteen toisen asteen koulutuksessa mahdollista suorittaa kaksoistutkinto?';
COMMENT ON COLUMN hakukohteet.kaytetaan_haun_aikataulua IS 'Käytetäänkö haun hakuaikoja vai onko hakukohteelle määritelty omat hakuajat?';
COMMENT ON COLUMN hakukohteet.valintaperuste_id IS 'Hakukohteeseen liittyvän valintaperustekuvauksen yksilöivä tunniste';
COMMENT ON COLUMN hakukohteet.liitteet_onko_sama_toimitusaika IS 'Onko kaikilla hakukohteen liitteillä sama toimitusaika?';
COMMENT ON COLUMN hakukohteet.liitteet_onko_sama_toimitusosoite IS 'Onko kaikilla hakukohteen liitteillä sama toimitusosoite?';
COMMENT ON COLUMN hakukohteet.liitteiden_toimitusaika IS 'Jos liitteillä on sama toimitusaika, se ilmoitetaan tässä';
COMMENT ON COLUMN hakukohteet.liitteiden_toimitustapa IS 'Jos liitteillä on sama toimitustapa, se ilmoitetaan tässä. Sallitut arvot: "hakijapalvelu", "osoite" ja "lomake".';
COMMENT ON COLUMN hakukohteet.liitteiden_toimitusosoite IS 'Jos liitteillä on sama toimitusosoite, se ilmoitetaan tässä. Osoite (katuosoite eri kielillä, postinumero, postitoimipaikka) ja sähköposti (sähköpostiosoite eri kielillä, johon liite voidaan toimittaa)';
COMMENT ON COLUMN hakukohteet.metadata IS ''; --TODO: Käytetäänkö?
COMMENT ON COLUMN hakukohteet.muokkaaja IS 'Hakukohdetta viimeksi muokanneen virkailijan henkilö-oid';
COMMENT ON COLUMN hakukohteet.kielivalinta IS 'Kielet, joille hakukohteen nimi, kuvailutiedot ja muut tekstit on käännetty';
COMMENT ON COLUMN hakukohteet.transaction_id IS 'Transaktion, jossa viimeksi muokattu, tunniste';
COMMENT ON COLUMN hakukohteet.system_time IS 'Hakukohteen viimeisin muokkausaika. Järjestelmän generoima';
COMMENT ON COLUMN hakukohteet.organisaatio_oid IS 'Hakukohteen luoneen organisaation oid';
COMMENT ON COLUMN hakukohteet.hakulomake_ataru_id IS 'Hakulomakkeen yksilöivä tunniste, jos käytössä on Atarun (hakemuspalvelun) hakulomake';
COMMENT ON COLUMN hakukohteet.hakulomake_linkki IS 'Hakulomakkeen linkki eri kielillä. Kielet on määritetty haun kielivalinnassa.';
COMMENT ON COLUMN hakukohteet.kaytetaan_haun_hakulomaketta IS 'Käytetäänkö haun hakulomaketta vai onko hakukohteelle määritelty oma hakulomake?';
COMMENT ON COLUMN hakukohteet.kaytetaan_haun_alkamiskautta IS 'Käytetäänkö haun alkamiskautta ja -vuotta vai onko hakukohteelle määritelty oma alkamisajankohta?';
COMMENT ON COLUMN hakukohteet.min_aloituspaikat IS 'Hakukohteen aloituspaikkojen minimimäärä';
COMMENT ON COLUMN hakukohteet.max_aloituspaikat IS 'Hakukohteen aloituspaikkojen maksimimäärä';
COMMENT ON COLUMN hakukohteet.min_ensikertalaisen_aloituspaikat IS 'Hakukohteen ensikertalaisen aloituspaikkojen minimimäärä';
COMMENT ON COLUMN hakukohteet.max_ensikertalaisen_aloituspaikat IS 'Hakukohteen ensikertalaisen aloituspaikkojen maksimimäärä';

COMMENT ON TABLE haut IS 'Haut';
COMMENT ON COLUMN haut.oid IS 'Haun yksilöivä tunniste. Järjestelmän generoima.';
COMMENT ON COLUMN haut.tila IS 'Haun julkaisutila. Jos haku on julkaistu, se näkyy oppijalle Opintopolussa. Sallitut arvot: "julkaistu", "arkistoitu", "tallennettu"';
COMMENT ON COLUMN haut.nimi IS 'Haun Opintopolussa näytettävä nimi eri kielillä. Kielet on määritetty koulutuksen kielivalinnassa.';
COMMENT ON COLUMN haut.hakutapa_koodi_uri IS 'Haun hakutapa. Viittaa koodistoon: https://virkailija.testiopintopolku.fi/koodisto-ui/html/koodisto/hakutapa/11';
COMMENT ON COLUMN haut.hakukohteen_liittamisen_takaraja IS 'Viimeinen ajanhetki, jolloin hakuun saa liittää hakukohteen. Hakukohteita ei saa lisätä enää sen jälkeen, kun haku on käynnissä.';
COMMENT ON COLUMN haut.hakukohteen_muokkaamisen_takaraja IS 'Viimeinen ajanhetki, jolloin hakuun liitettyä hakukohdetta on sallittua muokata. Hakukohteen tietoja ei saa muokata enää sen jälkeen, kun haku on käynnissä.';
COMMENT ON COLUMN haut.alkamiskausi_koodi_uri IS 'Haun koulutusten alkamiskausi. Hakukohteella voi olla eri alkamiskausi kuin haulla. Viittaa koodistoon: https://virkailija.testiopintopolku.fi/koodisto-ui/html/koodisto/kausi/1';
COMMENT ON COLUMN haut.alkamisvuosi IS 'Haun koulutusten alkamisvuosi. Hakukohteella voi olla eri alkamisvuosi kuin haulla.';
COMMENT ON COLUMN haut.kohdejoukko_koodi_uri IS 'Haun kohdejoukko. Viittaa koodistoon: https://virkailija.testiopintopolku.fi/koodisto-ui/html/koodisto/haunkohdejoukko/1';
COMMENT ON COLUMN haut.kohdejoukon_tarkenne_koodi_uri IS 'Haun kohdejoukon tarkenne. Viittaa koodistoon: https://virkailija.testiopintopolku.fi/koodisto-ui/html/koodisto/haunkohdejoukontarkenne/1';
COMMENT ON COLUMN haut.hakulomaketyyppi IS 'Hakulomakkeen tyyppi. Kertoo, käytetäänkö Atarun (hakemuspalvelun) hakulomaketta, muuta hakulomaketta (jolloin voidaan lisätä hakulomakkeeseen linkki) tai onko niin, ettei sähkököistä hakulomaketta ole lainkaan, jolloin sille olisi hyvä lisätä kuvaus. Hakukohteella voi olla eri hakulomake kuin haulla.';
COMMENT ON COLUMN haut.hakulomake_kuvaus IS 'Hakulomakkeen kuvausteksti eri kielillä. Kielet on määritetty haun kielivalinnassa. Hakukohteella voi olla eri hakulomake kuin haulla.';
COMMENT ON COLUMN haut.metadata IS 'Yleistä hakuun liittyvää metadataa: yhteyshenkilö ja tulevaisuuden aikataulu';
COMMENT ON COLUMN haut.organisaatio_oid IS 'Haun luoneen organisaation oid';
COMMENT ON COLUMN haut.muokkaaja IS 'Hakua viimeksi muokanneen virkailijan henkilö-oid';
COMMENT ON COLUMN haut.transaction_id IS 'Transaktion, jossa viimeksi muokattu, tunniste';
COMMENT ON COLUMN haut.system_time IS 'Haun viimeisin muokkausaika. Järjestelmän generoima';
COMMENT ON COLUMN haut.kielivalinta IS 'Kielet, joille haun nimi, kuvailutiedot ja muut tekstit on käännetty';
COMMENT ON COLUMN haut.ajastettu_julkaisu IS 'Ajanhetki, jolloin haku ja siihen liittyvät hakukohteet ja koulutukset julkaistaan automaattisesti Opintopolussa, jos ne eivät vielä ole julkisia';
COMMENT ON COLUMN haut.hakulomake_ataru_id IS 'Hakulomakkeen yksilöivä tunniste, jos käytössä on Atarun (hakemuspalvelun) hakulomake. Hakukohteella voi olla eri hakulomake kuin haulla.';
COMMENT ON COLUMN haut.hakulomake_linkki IS 'Hakulomakkeen linkki eri kielillä. Kielet on määritetty haun kielivalinnassa. Hakukohteella voi olla eri hakulomake kuin haulla.';

COMMENT ON TABLE valintaperusteet IS 'Valintaperusteiden sanalliset kuvaukset';
COMMENT ON COLUMN valintaperusteet.id IS 'Valintaperustekuvauksen yksilöivä tunniste. Järjestelmän generoima.';
COMMENT ON COLUMN valintaperusteet.tila IS 'Valintaperustekuvauksen julkaisutila. Jos kuvaus on julkaistu, se näkyy oppijalle Opintopolussa. Sallitut arvot: "julkaistu", "arkistoitu", "tallennettu"';
COMMENT ON COLUMN valintaperusteet.hakutapa_koodi_uri IS 'Valintaperustekuvaukseen liittyvä hakutapa. Viittaa koodistoon: https://virkailija.testiopintopolku.fi/koodisto-ui/html/koodisto/hakutapa/11';
COMMENT ON COLUMN valintaperusteet.kohdejoukko_koodi_uri IS 'Valintaperustekuvaukseen liittyvä kohdejoukko. Valintaperusteen ja siihen hakukohteen kautta liittyvän haun kohdejoukon tulee olla sama. Viittaa koodistoon: https://virkailija.testiopintopolku.fi/koodisto-ui/html/koodisto/haunkohdejoukko/1';
COMMENT ON COLUMN valintaperusteet.kohdejoukon_tarkenne_koodi_uri IS 'Valintaperustekuvaukseen liittyvä kohdejoukon tarkenne. Viittaa koodistoon: https://virkailija.testiopintopolku.fi/koodisto-ui/html/koodisto/haunkohdejoukontarkenne/1';
COMMENT ON COLUMN valintaperusteet.nimi IS 'Valintaperustekuvauksen Opintopolussa näytettävä nimi eri kielillä. Kielet on määritetty koulutuksen kielivalinnassa.';
COMMENT ON COLUMN valintaperusteet.kielivalinta IS 'Kielet, joille valintaperustekuvauksen nimi, kuvailutiedot ja muut tekstit on käännetty';
COMMENT ON COLUMN valintaperusteet.julkinen IS 'Voivatko muut oppilaitokset käyttää valintaperustekuvausta';
COMMENT ON COLUMN valintaperusteet.metadata IS 'Yleistä valintaperustekuvaukseen liittyvää metadataa: osaamistaustat, kuvaukset (eri kielillä) ja valintatavat';
COMMENT ON COLUMN valintaperusteet.organisaatio_oid IS 'Valintaperustekuvauksen luoneen organisaation oid';
COMMENT ON COLUMN valintaperusteet.muokkaaja IS 'Valintaperustekuvausta viimeksi muokanneen virkailijan henkilö-oid';
COMMENT ON COLUMN valintaperusteet.transaction_id IS 'Transaktion, jossa viimeksi muokattu, tunniste';
COMMENT ON COLUMN valintaperusteet.system_time IS 'Valintaperustekuvauksen viimeisin muokkausaika. Järjestelmän generoima';
COMMENT ON COLUMN valintaperusteet.koulutustyyppi IS 'Minkä tyyppisille koulutuksille valintaperustekuvaus on tarkoitettu käytettäväksi? Sallitut arvot: "amm" (ammatillinen), "yo" (yliopisto), "lk" (lukio), "mk" (ammattikorkea), "muu" (muu koulutus)';
COMMENT ON COLUMN valintaperusteet.sorakuvaus_id IS 'Valintaperustekuvaukseen liittyvän SORA-kuvauksen yksilöivä tunniste';

COMMENT ON TABLE sorakuvaukset IS 'SORA-kuvaukset eli opiskeluun soveltumattomuuteen ratkaisuja';
COMMENT ON COLUMN sorakuvaukset.id IS 'SORA-kuvauksen yksilöivä tunniste. Järjestelmän generoima.';
COMMENT ON COLUMN sorakuvaukset.tila IS 'SORA-kuvauksen julkaisutila. Jos SORA-kuvaus on julkaistu, se näkyy oppijalle Opintopolussa. Sallitut arvot: "julkaistu", "arkistoitu", "tallennettu"';
COMMENT ON COLUMN sorakuvaukset.nimi IS 'SORA-kuvauksen Opintopolussa näytettävä nimi eri kielillä. Kielet on määritetty SORA-kuvauksen kielivalinnassa.';
COMMENT ON COLUMN sorakuvaukset.koulutustyyppi IS 'Minkä tyyppisiin koulutuksiin SORA-kuvaus liittyy. Sallitut arvot: ''amm'' (ammatillinen), ''yo'' (yliopisto), ''lk'' (lukio), ''amk'' (ammattikorkea), ''muu'' (muu koulutus)';
COMMENT ON COLUMN sorakuvaukset.julkinen IS 'Voivatko muut oppilaitokset käyttää SORA-kuvausta';
COMMENT ON COLUMN sorakuvaukset.kielivalinta IS 'Kielet, joille SORA-kuvauksen nimi, kuvailutiedot ja muut tekstit on käännetty';
COMMENT ON COLUMN sorakuvaukset.metadata IS 'SORA-kuvauksen kuvailutiedot eri kielillä';
COMMENT ON COLUMN sorakuvaukset.organisaatio_oid IS 'SORA-kuvauksen luoneen organisaation oid';
COMMENT ON COLUMN sorakuvaukset.muokkaaja IS 'SORA-kuvausta viimeksi muokanneen virkailijan henkilö-oid';
COMMENT ON COLUMN sorakuvaukset.transaction_id IS 'Transaktion, jossa viimeksi muokattu, tunniste';
COMMENT ON COLUMN sorakuvaukset.system_time IS 'SORA-kuvauksen viimeisin muokkausaika. Järjestelmän generoima';

COMMENT ON TABLE koulutusten_tarjoajat IS 'Koulutusta tarjoavien organisaatioden tiedot';
COMMENT ON COLUMN koulutusten_tarjoajat.koulutus_oid IS 'Koulutuksen yksilöivä tunniste';
COMMENT ON COLUMN koulutusten_tarjoajat.tarjoaja_oid IS 'Koulutusta tarjoavan organisaation yksilöivä tunniste';
COMMENT ON COLUMN koulutusten_tarjoajat.muokkaaja IS 'Koulutuksen organisaation liittäneen virkailijan henkilö-oid';
COMMENT ON COLUMN koulutusten_tarjoajat.transaction_id IS 'Transaktion, jossa viimeksi muokattu, tunniste';
COMMENT ON COLUMN koulutusten_tarjoajat.system_time IS 'Viimeisin muokkausaika. Järjestelmän generoima';

COMMENT ON TABLE toteutusten_tarjoajat IS 'Koulutuksen toteutusta järjestävien organisaatioden tiedot';
COMMENT ON COLUMN toteutusten_tarjoajat.toteutus_oid IS 'Koulutuksen toteutuksen yksilöivä tunniste';
COMMENT ON COLUMN toteutusten_tarjoajat.tarjoaja_oid IS 'Koulutusta toteutusta järjestävän organisaation yksilöivä tunniste';
COMMENT ON COLUMN toteutusten_tarjoajat.muokkaaja IS 'Koulutuksen toteutuksen organisaatioon liittäneen virkailijan henkilö-oid';
COMMENT ON COLUMN toteutusten_tarjoajat.transaction_id IS 'Transaktion, jossa viimeksi muokattu, tunniste';
COMMENT ON COLUMN toteutusten_tarjoajat.system_time IS 'Viimeisin muokkausaika. Järjestelmän generoima';

COMMENT ON TABLE hakukohteiden_valintakokeet IS 'Hakukohteiden valintakokeiden tiedot';
COMMENT ON COLUMN hakukohteiden_valintakokeet.id IS 'Valintakokeen yksilöivä tunniste. Järjestelmän generoima.';
COMMENT ON COLUMN hakukohteiden_valintakokeet.hakukohde_oid IS 'Valintakokeen hakukohteen yksilöivä tunniste.';
COMMENT ON COLUMN hakukohteiden_valintakokeet.tyyppi IS 'Valintakokeen tyyppi. Viittaa koodistoon: https://virkailija.testiopintopolku.fi/koodisto-ui/html/koodisto/valintakokeentyyppi/1';
COMMENT ON COLUMN hakukohteiden_valintakokeet.tilaisuudet IS 'Valintakokeen järjestämistilaisuudet: osoite, aika ja lisätietoja ';
COMMENT ON COLUMN hakukohteiden_valintakokeet.muokkaaja IS 'Valintakoetta viimeksi muokanneen virkailijan henkilö-oid';
COMMENT ON COLUMN hakukohteiden_valintakokeet.transaction_id IS '';
COMMENT ON COLUMN hakukohteiden_valintakokeet.system_time IS 'Valintakokeen viimeisin muokkausaika. Järjestelmän generoima';

COMMENT ON TABLE hakukohteiden_liitteet IS 'Hakukohteiden liitteiden tiedot';
COMMENT ON COLUMN hakukohteiden_liitteet.id IS 'Liitteen yksilöivä tunniste. Järjestelmän generoima.';
COMMENT ON COLUMN hakukohteiden_liitteet.hakukohde_oid IS 'Liitteen hakukohteen yksilöivä tunniste.';
COMMENT ON COLUMN hakukohteiden_liitteet.tyyppi IS 'Liitteen tyyppi. Viittaa koodistoon: https://virkailija.testiopintopolku.fi/koodisto-ui/html/koodisto/liitetyypitamm/1';
COMMENT ON COLUMN hakukohteiden_liitteet.nimi IS '	Liitteen Opintopolussa näytettävä nimi eri kielillä. Kielet on määritetty hakukohteen kielivalinnassa';
COMMENT ON COLUMN hakukohteiden_liitteet.kuvaus IS 'Liitteen Opintopolussa näytettävä kuvaus eri kielillä. Kielet on määritetty hakukohteen kielivalinnassa.';
COMMENT ON COLUMN hakukohteiden_liitteet.toimitusaika IS 'Liitteen toimitusaika, jos ei ole sama kuin kaikilla hakukohteen liitteillä';
COMMENT ON COLUMN hakukohteiden_liitteet.toimitustapa IS 'Liitteen toimitustapa, jos ei ole sama kuin kaikilla hakukohteen liitteillä. Sallitut arvot: "hakijapalvelu", "osoite" ja "lomake"';
COMMENT ON COLUMN hakukohteiden_liitteet.toimitusosoite IS 'Jos liitteillä on sama toimitusosoite, se ilmoitetaan tässä. Osoite (katuosoite eri kielillä, postinumero, postitoimipaikka) ja sähköposti (sähköpostiosoite eri kielillä, johon liite voidaan toimittaa)';
COMMENT ON COLUMN hakukohteiden_liitteet.muokkaaja IS 'Liitettä viimeksi muokanneen virkailijan henkilö-oid';
COMMENT ON COLUMN hakukohteiden_liitteet.transaction_id IS 'Transaktion, jossa viimeksi muokattu, tunniste';
COMMENT ON COLUMN hakukohteiden_liitteet.system_time IS 'Liitteen viimeisin muokkausaika. Järjestelmän generoima';

COMMENT ON TABLE hakukohteiden_hakuajat IS 'Hakukohteen hakuajat, jos ei käytetä haun hakuaikoja';
COMMENT ON COLUMN hakukohteiden_hakuajat.hakukohde_oid IS 'Hakuajan hakukohteen yksilöivä tunniste.';
COMMENT ON COLUMN hakukohteiden_hakuajat.hakuaika IS 'Hakuaika (aikaväli)';
COMMENT ON COLUMN hakukohteiden_hakuajat.muokkaaja IS 'Hakuaikaa viimeksi muokanneen virkailijan henkilö-oid';
COMMENT ON COLUMN hakukohteiden_hakuajat.transaction_id IS 'Transaktion, jossa viimeksi muokattu, tunniste';
COMMENT ON COLUMN hakukohteiden_hakuajat.system_time IS 'Hakuaikaa viimeisin muokkausaika. Järjestelmän generoima';

COMMENT ON TABLE hakujen_valintakokeet IS 'Hakujen valintakokeiden tiedot';
COMMENT ON COLUMN hakujen_valintakokeet.id IS 'Valintakokeen yksilöivä tunniste. Järjestelmän generoima.';
COMMENT ON COLUMN hakujen_valintakokeet.haku_oid IS 'Valintakokeen haun yksilöivä tunniste.';
COMMENT ON COLUMN hakujen_valintakokeet.tyyppi IS 'Valintakokeen tyyppi. Viittaa koodistoon: https://virkailija.testiopintopolku.fi/koodisto-ui/html/koodisto/valintakokeentyyppi/1';
COMMENT ON COLUMN hakujen_valintakokeet.tilaisuudet IS 'Valintakokeen järjestämistilaisuudet: osoite, aika ja lisätietoja ';
COMMENT ON COLUMN hakujen_valintakokeet.muokkaaja IS 'Valintakoetta viimeksi muokanneen virkailijan henkilö-oid';
COMMENT ON COLUMN hakujen_valintakokeet.transaction_id IS 'Transaktion, jossa viimeksi muokattu, tunniste';
COMMENT ON COLUMN hakujen_valintakokeet.system_time IS 'Valintakokeen viimeisin muokkausaika. Järjestelmän generoima';

COMMENT ON TABLE hakujen_hakuajat IS 'Haun hakuajat. Hakukohteella voi olla omat hakuajat.';
COMMENT ON COLUMN hakujen_hakuajat.haku_oid IS 'Hakuajan haun yksilöivä tunniste.';
COMMENT ON COLUMN hakujen_hakuajat.hakuaika IS 'Hakuaika (aikaväli)';
COMMENT ON COLUMN hakujen_hakuajat.muokkaaja IS 'Hakuaikaa viimeksi muokanneen virkailijan henkilö-oid';
COMMENT ON COLUMN hakujen_hakuajat.transaction_id IS 'Transaktion, jossa viimeksi muokattu, tunniste';
COMMENT ON COLUMN hakujen_hakuajat.system_time IS 'Hakuaikaa viimeisin muokkausaika. Järjestelmän generoima';

COMMENT ON TABLE asiasanat IS 'Koulutusten toteutuksien asiasanat';
COMMENT ON COLUMN asiasanat.asiasana IS 'Asiasana';
COMMENT ON COLUMN asiasanat.kieli IS 'Asiasanan kieli. Sallitut arvot: "fi", "sv" ja "en"';

COMMENT ON TABLE ammattinimikkeet IS 'Koulutusten toteutuksien ammattinimikkeet';
COMMENT ON COLUMN ammattinimikkeet.ammattinimike IS 'Ammattinimke';
COMMENT ON COLUMN ammattinimikkeet.kieli IS 'Ammattinimikkeen kieli. Sallitut arvot: "fi", "sv" ja "en"';

COMMENT ON TABLE sessions IS 'Virkailijoiden istuntojen tiedot';
COMMENT ON COLUMN sessions.id IS 'Istunnon yksilöivä tunniste. Järjestelmän generoima.';
COMMENT ON COLUMN sessions.cas_ticket IS 'CAS-autentikointijärjestelmän service ticketin (ST) tunniste';
COMMENT ON COLUMN sessions.person IS 'Virkailijan henkilö-oid';
COMMENT ON COLUMN sessions.last_read IS '';

COMMENT ON TABLE authorities IS 'Virkailijoiden istuntoihin liittyvät käyttöoikeudet';
COMMENT ON COLUMN authorities.session IS 'Käyttöoikeuteen liittyvän istunnon yksilöivä tunniste';
COMMENT ON COLUMN authorities.authority IS 'Käyttöoikeuden tunniste (organisaation oid + itse käyttöoikeus)';