#!/usr/bin/env bash

id_file="$HOME/.kouta_localstack"
localstack_version=latest

wait_for_ready () {
    echo "Wait for services to be started..."
    id=$(cat ${id_file})
    wait=120
    while [[ ${wait} > 0 ]]
    do
        if [[ $(docker logs ${id} --tail 1) == *"Ready."* ]]
        then
            started=true
            return
        else
            sleep 1
            wait=$(expr ${wait} - 1)
        fi
    done
}

create_queues () {
    export AWS_ACCESS_KEY_ID="randomKeyIdForLocalstack"
    export AWS_SECRET_ACCESS_KEY="randomKeyForLocalstack"

    config="$(dirname ${BASH_SOURCE[0]})/queue-config.json"
    notifications_config="$(dirname ${BASH_SOURCE[0]})/notifications-queue-config.json"

    echo "Creating queues for service"
    aws --endpoint-url http://localhost:4566 --output text sqs create-queue --region eu-west-1 --queue-name koutaIndeksoijaDlq
    aws --endpoint-url http://localhost:4566 --output text sqs create-queue --region eu-west-1 --queue-name koutaIndeksoijaPriority --attributes file://${config}
    aws --endpoint-url http://localhost:4566 --output text sqs create-queue --region eu-west-1 --queue-name koutaIndeksoijaFast     --attributes file://${config}
    aws --endpoint-url http://localhost:4566 --output text sqs create-queue --region eu-west-1 --queue-name koutaIndeksoijaSlow     --attributes file://${config}
    aws --endpoint-url http://localhost:4566 --output text sqs create-queue --region eu-west-1 --queue-name koutaIndeksoijaNotificationsDlq
    aws --endpoint-url http://localhost:4566 --output text sqs create-queue --region eu-west-1 --queue-name koutaIndeksoijaNotifications --attributes file://${notifications_config}

    echo "Created queues"
}

start_container() {
    echo "Starting Localstack container"
    docker run -d -p 4566:4566 localstack/localstack:${localstack_version} > ${id_file}
    echo "Container started"
}

if [[ -f ${id_file} ]]; then
    echo "Localstack environment is already running. '${id_file}' file found."
    exit 0
else
    start_container
    wait_for_ready
    if [[ ${started} ]]
    then
        echo "Services are started."
        create_queues
    else
        echo "Failed to start services. Shutting down container"
        ./tools/stop_localstack
        exit 1
    fi
fi
