#!/usr/bin/env bash

id_file="$HOME/.kouta_localstack"

if [[ -f ${id_file} ]]
then
    id=$(cat ${id_file})
    echo "Stopping container $(docker stop ${id})"
    rm ${id_file}
    echo "Localstack stopped"
else
    echo "Localstack environment not running. '${id_file}' file not found."
fi

